/*
  romi-rover

  Copyright (C) 2019 Sony Computer Science Laboratories
  Author(s) Peter Hanappe

  romi-rover is collection of applications for the Romi Rover.

  romi-rover is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see
  <http://www.gnu.org/licenses/>.

 */
#ifndef __ROMI_SERIAL_ERRORS_H
#define __ROMI_SERIAL_ERRORS_H

enum {
        romiserial_error_none = 0,

        romiserial_unexpected_char = -1,
        romiserial_invalid_id = -2,
        romiserial_invalid_crc = -3,
        romiserial_crc_mismatch = -4,
        romiserialclient_connection_failed = -5,
        romiserialclient_unexpected_char = -6,
        romiserialclient_crc_mismatch = -7,
        romiserialclient_invalid_json = -8,
        romiserialclient_connection_timeout = -9,
        romiserialclient_invalid_error = -10,
        romiserial_last_protocol_error = -11,

        // Errors generated by the RomiSerial parser 
        romiserial_vector_too_long = -100,
        romiserial_value_out_of_range = -101,
        romiserial_string_too_long = -102,
        romiserial_invalid_string = -103,
        romiserial_too_many_strings = -104,
        romiserial_too_long = -105,
        romiserial_invalid_opcode = -106,

        // Errors generated by RomiSerial 
        romiserial_unknown_opcode = -110,
        romiserial_bad_number_of_arguments = -111,
        romiserial_missing_string = -112,
        romiserial_bad_string = -113,
        romiserial_bad_handler = -114,
        romiserial_duplicate = -115,

        // Errors generated by RomiSerialClient 
        romiserialclient_invalid_opcode = -201,
        romiserialclient_too_long = -202,
        romiserialclient_empty_request = -203,
};

#endif
