/*
  romi-rover

  Copyright (C) 2019 Sony Computer Science Laboratories
  Author(s) Peter Hanappe

  romi-rover is collection of applications for the Romi Rover.

  romi-rover is free software: you can redistribute it and/or modify
  it under the terms of the GNU General Public License as published by
  the Free Software Foundation, either version 3 of the License, or
  (at your option) any later version.

  This program is distributed in the hope that it will be useful, but
  WITHOUT ANY WARRANTY; without even the implied warranty of
  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
  General Public License for more details.

  You should have received a copy of the GNU General Public License
  along with this program.  If not, see
  <http://www.gnu.org/licenses/>.

 */
#ifndef __ROMI_SERIAL_ERRORS_H
#define __ROMI_SERIAL_ERRORS_H

enum {
        romiserial_error_none = 0,

        // Errors generated by the RomiSerial parser 
        romiserial_unexpected_char = -1,
        romiserial_vector_too_long = -2,
        romiserial_value_out_of_range = -3,
        romiserial_string_too_long = -4,
        romiserial_invalid_string = -5,
        romiserial_too_many_strings = -6,
        romiserial_invalid_id = -7,
        romiserial_invalid_crc = -8,
        romiserial_crc_mismatch = -9,
        romiserial_too_long = -10,
        romiserial_invalid_opcode = -11,

        // Errors generated by RomiSerial 
        romiserial_unknown_opcode = -100,
        romiserial_bad_number_of_arguments = -101,
        romiserial_missing_string = -102,
        romiserial_bad_string = -103,
        romiserial_bad_handler = -104,

        // Errors generated by RomiSerialClient 
        romiserialclient_connection_failed = -200,
        romiserialclient_unexpected_char = -201,
        romiserialclient_invalid_opcode = -202,
        romiserialclient_crc_mismatch = -203,
        romiserialclient_invalid_json = -204,
        romiserialclient_connection_timeout = -205,
        romiserialclient_invalid_error = -206,
        romiserialclient_too_long = -207,
};

#endif
