#ifndef _OQUAM_CONFIG_H_
#define _OQUAM_CONFIG_H_

//#define ENABLE_PIN_HIGH 0
#define ENABLE_PIN_HIGH 1

//#define ENCODER_REVERSED 0
#define ENCODER_REVERSED 1

#define PRESCALING 1
#define FREQUENCY_STEPPER 25000
#define INTERRUPTS_PER_MILLISECOND 25

//#define PRESCALING 8
//#define FREQUENCY_STEPPER 10000
//#define INTERRUPTS_PER_MILLISECOND 10

#endif // _OQUAM_CONFIG_H_
